apiVersion: v1
kind: Service
metadata:
  name: is-exam-service
spec:
  selector:
    app: entrypoint-service
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: entrypoint-service
spec:
  selector:
    matchLabels:
      app: entrypoint-service
  replicas: 1
  template:
    metadata:
      labels:
        app: entrypoint-service
    spec:
      containers:
      - name: entrypoint-service
        image: docker.io/lauridsand/entrypoint-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dependent-service
spec:
  selector:
    matchLabels:
      app: dependent-service
  replicas: 1
  template:
    metadata:
      labels:
        app: dependent-service
    spec:
      containers:
      - name: dependent-service
        image: docker.io/lauridsand/dependent-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5001