apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: is-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
        - path: /
          backend:
            serviceName: entrypoint-service
            servicePort: 80
---

### entrypoint
apiVersion: apps/v1
kind: Deployment
metadata:
  name: entrypoint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: entrypoint
  template:
    metadata:
      labels:
        app: entrypoint
    spec:
      containers:
      - name: entrypoint
        image: docker.io/lauridsand/entrypoint-service:latest
        ports:
        - containerPort: 8080
---

kind: Service
apiVersion: v1
metadata:
  name: entrypoint-service
spec:
  selector:
    app: entrypoint
    ports:
      - port: 80
        targetPort: 8080
        protocol: TCP
        name: http
      selector:
        app: entrypoint
---

### dependent
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dependent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dependent
  template:
    metadata:
      labels:
        app: dependent
    spec:
      containers:
      - name: dependent
        image: docker.io/lauridsand/dependent-service:latest
        ports:
        - containerPort: 8080
---

kind: Service
apiVersion: v1
metadata:
  name: dependent-service
spec:
  selector:
    app: dependent
  ports:
    - port: 80
